---
title: "Model Development"
author: "Andrew Holguin"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Energy Intensity}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
---

Calculating energy intensity requires all of the water and energy meter data
associated with an asset to be combined and reconciled.

Cleaning and pre-processing of the data can be handled entirely by the analyst,
however, there are a few approaches built in to the `energyintensity` package,
which implement commonly used methods. These methods are used to standardize the
different time series, so that they can be merged and aggregated. The available
methods fall into two general categories: (1) aggregation, and (2) resampling.


### Asset Meter Data

- support point and interval measurements (and conversion)
- time series vis & diagnostics
- app to support review and validation



### Network Connectivity Model

- display (and edit?) connectivity



### Data Integration

- associate meter data with specific nodes or edges in the graph



### Network Time Slices

- snapshot of model during a point or interval of time
- cumulative flow and related diagnostics



### Model Execution

- calc ei & flow



### Data Fusion & Model Tuning

- e.g., flow/usage data reconciliation



## Future Development Plans

Split non-core components into other packages:
  - random data generation for simulation and testing
  - model development vis app
  - additional extensions?

- network skeletonization
- integration with external hydraulic models
- better representation of time lags and storage
- additional and improved analytical tools
- more tests, documentation, etc.


